### ISSUE TITLE
Cyrillic letters issue

### ISSUE THREAD

**Issue by haubna** [fabmax/physx-jni#29]
Caused by cyrillic letters in the username

```
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\?????? ?????\AppData\Local\Temp\de.fabmax.physx-jni\0.4.13\PhysX_64.dll: Can't find dependent libraries
--
  | at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
  | at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
  | at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
  | at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
  | at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
  | at java.base/java.lang.Runtime.load0(Runtime.java:746)
  | at java.base/java.lang.System.load(System.java:1857)
  | at de.fabmax.physxjni.Loader.loadLibsFromResources(Loader.java:71)
  | at de.fabmax.physxjni.Loader.load(Loader.java:33)
  | ... 14 more
```

**Comment by fabmax** [comment]
This seems to be a Java bug: https://bugs.openjdk.java.net/browse/JDK-8195129

Maybe it could be a workaround to check the temp dir path for unicode characters and choose a different temp location if that is the case.
